apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: xgboost-minio
spec:
  name: cardio-xgb-minio
  predictors:
    - graph:
        children: []
        implementation: XGBOOST_SERVER
        modelUri: s3://seldon-models/cardio
        envSecretRefName: seldon-init-container-secret
        name: classifier
      name: default
      replicas: 1
